config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/about', to: 'static_pages#about'

  resources :pages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

## These are all Read Methods, the Controller appears to be mostly a read program

  def index
    @notes = Note.all 
    ## Shows all pages in the database

  end

  def show
    @notes = Note.find(params[:id])
    ## find a page by the ID passed in
  end

  def new
  @notes = Note.new
  ##Creates a new page in memory that is not yet saved to the db
  end
end

def create
  @note = Note.new(pages_params)
  
  if @note.save
    redirect_to notes_path
  else
    render :new
  end
end

def edit
  @note = Notes.find(params[:id])
  # render :_form #Points to the _form.html.erb form partial or something like that.
end

def update
  @note = Note.find(params[:id])
  if @note.update(page_params)
    redirect_to note_path
  else
    render :edit
  end
end

def destroy
  @note.destroy
  Note.find(params[:id]).destroy
  redirect_to note_path
end


private

  def notes_params 
    params.require(:note).permit(:title, :author, :body)
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'About', about_path %>
<%= link_to 'Notes', pages_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostIt</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
  <%= render 'layouts/navbar' %>
  <%= yield %>
</body>
</html>

app/views/notes/edit.html.erb
<h1>Edit Note</h1>
<%= form_for @note do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit %>
<% end %>
<p>Find me in app/views/notes/edit.html.erb</p>

app/views/notes/index.html.erb
<h1> Notes </h1>
<% @notes.each do |note| %>
  <h2><%= note.title %></h2>
<p><%= link_to 'New Note', new_note_path %></p>
<%= link_to 'Edit note', edit_note_path(note) %>
<%= link_to 'Show Note', note_path(page) %>
<% end %>

app/views/notes/new.html.erb
<h1>Notes#new</h1>
<h1>New Note</h1>
<%= form_for @note do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit %>
<% end %>
<p>Find me in app/views/notes/new.html.erb</p>

app/views/notes/show.html.erb
<h1>Notes#show</h1>
<p>Find me in app/views/notes/show.html.erb</p>

app/views/pages/index.html.erb
# <h1>Pages#index</h1>
# <p>Find me in app/views/pages/index.html.erb</p>


<h1> Notes </h1>
<% @notes.each do |note| %>
  <h2><%= note.title %></h2>
<p><%= link_to 'New Note', new_note_path %></p>
<%= link_to 'Edit note', edit_note_path(note) %>
<%= link_to 'Show Note', note_path(page) %>
<% end %>

app/views/pages/new.html.erb
# <h1>Pages#new</h1>
# <p>Find me in app/views/pages/new.html.erb</p>


<h1>New Page</h1>
<%= form_for @page do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit %>
<% end %>

app/views/pages/show.html.erb
# <h1>Pages#show</h1>
# <p>Find me in app/views/pages/show.html.erb</p>

<h1><%= @page.title %></h1>
<h4><%= @page.author %></h1>
<p><%= @page.body %></p>
<%= link_to 'Back', pages_path %>